NDefines.NGame.START_DATE = "2061.1.1.1"
NDefines.NGame.END_DATE = "2076.12.31.1"
NDefines.NFocus.FOCUS_POINT_DAYS = 1
NDefines.NGame.FUEL_RESOURCE = electricity

NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 200
NDefines.NFrontend.CAMERA_MIN_HEIGHT = 40.0
NDefines.NFrontend.CAMERA_MAX_HEIGHT = 4000 -- CHANGE TO ABOUT 3500-4000 FOR A FULL MAP TEASER IF NEEDED
NDefines_Graphics.NGraphics.POLITICAL_GRID_SMALL_BOX_LIMIT = 100